/*
 * Bumble Bots Re-Pair, a Gamebuino game
 *
 * Copyright 2020, Erwin Bonsma
 */

#include "Song.h"

namespace Gamebuino_Meta {

// This file is automatically generated using import-from-p8.py
//
// Manually patched to:
// - Use full volume range
// - Remove duplicate patterns
// - Reduce volume of some echo notes
// - Bump volume of bass tunes
// - Tweak some NOISE notes

const NoteSpec sfx16NotesBumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
};
const TuneSpec sfx16BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx16NotesBumbleBots
};
const NoteSpec sfx17NotesBumbleBots[32] = {
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx17BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx17NotesBumbleBots
};
const NoteSpec sfx18NotesBumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Gs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx18BumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx18NotesBumbleBots
};
const NoteSpec sfx19NotesBumbleBots[32] = {
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx19BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx19NotesBumbleBots
};
const NoteSpec sfx20NotesBumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx20BumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx20NotesBumbleBots
};
const NoteSpec sfx21NotesBumbleBots[32] = {
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx21BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx21NotesBumbleBots
};
const NoteSpec sfx22NotesBumbleBots[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx22BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx22NotesBumbleBots
};
const NoteSpec sfx23NotesBumbleBots[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx23BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx23NotesBumbleBots
};
const NoteSpec sfx24NotesBumbleBots[32] = {
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx24BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx24NotesBumbleBots
};
const NoteSpec sfx25NotesBumbleBots[32] = {
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx25BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx25NotesBumbleBots
};
const NoteSpec sfx26NotesBumbleBots[32] = {
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
};
const TuneSpec sfx26BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx26NotesBumbleBots
};
const NoteSpec sfx27NotesBumbleBots[32] = {
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx27BumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx27NotesBumbleBots
};
const NoteSpec sfx28NotesBumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
};

const TuneSpec *const pattern0TunesBumbleBots[1] = { &sfx16BumbleBots };
const PatternSpec pattern0BumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern0TunesBumbleBots
};
const TuneSpec *const pattern1TunesBumbleBots[1] = { &sfx17BumbleBots };
const PatternSpec pattern1BumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern1TunesBumbleBots
};
const TuneSpec *const pattern3TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx18BumbleBots };
const PatternSpec pattern3BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern3TunesBumbleBots
};
const TuneSpec *const pattern4TunesBumbleBots[2] = { &sfx17BumbleBots, &sfx19BumbleBots };
const PatternSpec pattern4BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern4TunesBumbleBots
};
const TuneSpec *const pattern5TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx20BumbleBots };
const PatternSpec pattern5BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern5TunesBumbleBots
};
const TuneSpec *const pattern6TunesBumbleBots[2] = { &sfx17BumbleBots, &sfx21BumbleBots };
const PatternSpec pattern6BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern6TunesBumbleBots
};
const TuneSpec *const pattern7TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx22BumbleBots };
const PatternSpec pattern7BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern7TunesBumbleBots
};
const TuneSpec *const pattern8TunesBumbleBots[2] = { &sfx17BumbleBots, &sfx23BumbleBots };
const PatternSpec pattern8BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern8TunesBumbleBots
};
const TuneSpec *const pattern9TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx24BumbleBots };
const PatternSpec pattern9BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern9TunesBumbleBots
};
const TuneSpec *const pattern10TunesBumbleBots[2] = { &sfx17BumbleBots, &sfx25BumbleBots };
const PatternSpec pattern10BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern10TunesBumbleBots
};
const TuneSpec *const pattern11TunesBumbleBots[3] = { &sfx16BumbleBots, &sfx24BumbleBots, &sfx18BumbleBots };
const PatternSpec pattern11BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern11TunesBumbleBots
};
const TuneSpec *const pattern12TunesBumbleBots[3] = { &sfx17BumbleBots, &sfx25BumbleBots, &sfx19BumbleBots };
const PatternSpec pattern12BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern12TunesBumbleBots
};
const TuneSpec *const pattern13TunesBumbleBots[3] = { &sfx16BumbleBots, &sfx24BumbleBots, &sfx20BumbleBots };
const PatternSpec pattern13BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern13TunesBumbleBots
};
const TuneSpec *const pattern14TunesBumbleBots[3] = { &sfx17BumbleBots, &sfx25BumbleBots, &sfx21BumbleBots };
const PatternSpec pattern14BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern14TunesBumbleBots
};
const TuneSpec *const pattern15TunesBumbleBots[3] = { &sfx16BumbleBots, &sfx24BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern15BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern15TunesBumbleBots
};
const TuneSpec *const pattern16TunesBumbleBots[3] = { &sfx17BumbleBots, &sfx25BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern16BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern16TunesBumbleBots
};
const TuneSpec *const pattern17TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern17BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern17TunesBumbleBots
};
const TuneSpec *const pattern18TunesBumbleBots[2] = { &sfx16BumbleBots, &sfx27BumbleBots };
const PatternSpec pattern18BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern18TunesBumbleBots
};
const TuneSpec *const pattern19TunesBumbleBots[3] = { &sfx16BumbleBots, &sfx18BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern19BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern19TunesBumbleBots
};
const TuneSpec *const pattern20TunesBumbleBots[3] = { &sfx17BumbleBots, &sfx19BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern20BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern20TunesBumbleBots
};
const TuneSpec *const pattern21TunesBumbleBots[3] = { &sfx16BumbleBots, &sfx20BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern21BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern21TunesBumbleBots
};
const TuneSpec *const pattern22TunesBumbleBots[3] = { &sfx17BumbleBots, &sfx21BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern22BumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern22TunesBumbleBots
};
const TuneSpec *const pattern23TunesBumbleBots[2] = { &sfx24BumbleBots, &sfx26BumbleBots };
const PatternSpec pattern23BumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern23TunesBumbleBots
};

const PatternSpec *const song0PatternsBumbleBots[25] = {
    &pattern0BumbleBots,
    &pattern1BumbleBots,
    &pattern1BumbleBots,
    &pattern3BumbleBots,
    &pattern4BumbleBots,
    &pattern5BumbleBots,
    &pattern6BumbleBots,
    &pattern7BumbleBots,
    &pattern8BumbleBots,
    &pattern9BumbleBots,
    &pattern10BumbleBots,
    &pattern11BumbleBots,
    &pattern12BumbleBots,
    &pattern13BumbleBots,
    &pattern14BumbleBots,
    &pattern15BumbleBots,
    &pattern16BumbleBots,
    &pattern17BumbleBots,
    &pattern18BumbleBots,
    &pattern19BumbleBots,
    &pattern20BumbleBots,
    &pattern21BumbleBots,
    &pattern22BumbleBots,
    &pattern23BumbleBots,
    &pattern23BumbleBots,
};
const SongSpec song0BumbleBots = SongSpec {
    .loopStart = 9, .numPatterns = 25, .patterns = song0PatternsBumbleBots
};

} // Namespace

const Gamebuino_Meta::SongSpec* bumbleBotsSong = &Gamebuino_Meta::song0BumbleBots;
